version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: ./ollama/Dockerfile
    container_name: terraform-llm-ollama
    volumes:
      - ./shared:/shared
      - ollama-data:/root/.ollama
    ports:
      - "8000:8000"
      - "11434:11434"
    restart: unless-stopped
    networks:
      - terraform-llm-network

  terraform:
    build:
      context: .
      dockerfile: ./terraform/Dockerfile
    container_name: terraform-llm-terraform
    volumes:
      - ./shared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8001:8001"
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - terraform-llm-network

volumes:
  ollama-data:

networks:
  terraform-llm-network:
    driver: bridge